### ISSUE TITLE
如何把项目在本机上运行起来?

### ISSUE THREAD

**Issue by despagito** [gefangshuai/ANodeBlog#2]
我将代码下载到本地之后,安装依赖

```
npm install
```

然后

```
npm start
```

就会报错.

刚开始入门node,请问要如何使项目正确运行呢?

**Comment by lifedever** [comment]
请问报什么错呢？能否把错误贴上来？

首先检查mongodb是否运行，然后检查config.js中数据库的连接对不对？

我猜八成是数据库那块报错了。mongodb每次要手动起一下服务，点`startup.bat`

**Comment by despagito** [comment]
错误已经解决了,是我本机上没有安装mongodb的原因,安装完mongodb之后,新建一个blog的数据库之后,就可以`npm start`运行起来了,建议在文章中说明一下需要安装mongodb.

**Comment by lifedever** [comment]
项目本来就依托`mongodb`来做数据库进行存储，所以安装mongodb是必然的……
